# -*- coding: utf-8 -*-
"""rockormine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1K-urESP_543xloeMLF3f_jVvN6xijHtk
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
data=pd.read_csv('/content/Copy of sonar data.csv',header=None)
X=data.drop(columns=60,axis=1)
Y=data[60]
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,random_state=2,stratify=Y)
model=LogisticRegression()
model.fit(X_train,Y_train)
prediction=model.predict(X_test)
score=accuracy_score(prediction,Y_test)
print(score*100)