# -*- coding: utf-8 -*-
"""ROCKMINE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lpoLcpW-7ND12TrsdNMOZxStrU9JOmtI
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

data=pd.read_csv('/content/Copy of sonar data.csv',header=None)

data.shape

data.describe()

data[60].value_counts()

X=data.drop(columns=60,axis=1)
Y=data[60]
print(X)
print(Y)

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.1,stratify=Y,random_state=1)

model=LogisticRegression()

model.fit(X_train,Y_train)

trainpred=model.predict(X_train)
accuracy=accuracy_score(trainpred,Y_train)
print(accuracy)

prediction=model.predict(X_test)
acc=accuracy_score(prediction,Y_test)
print(acc)